# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: sink
description: >
  Old copes retirement home
#baseurl: "jmk" # the subpath of your site, e.g. /blog
url: "http://justinmk.github.io" # base hostname & protocol for your site
twitter_username: justinmk
github_username:  justinmk
permalink: /jmk/:title

ga_tracking_id: UA-12678461-4

# Build settings
markdown: kramdown
